# Configuration for probot-no-response - https://github.com/probot/no-response

# Number of days of inactivity before an Issue is closed for lack of response
daysUntilClose: 21
# Label requiring a response
responseRequiredLabel: "more info required"
# Comment to post when closing an Issue for lack of response. Set to `false` to disable
closeComment: >
  Without additional information, we are unfortunately not sure how to
  resolve this issue. Therefore this issue has been automatically closed.
  Feel free to comment with additional details and we can re-open this issue.
